import { ServiceCategory } from '@prisma/client';

export interface Specialization {
  id: string;
  title: string;
  category: ServiceCategory;
}

export const specializations: Record<ServiceCategory, Specialization[]> = {
  CONSTRUCTION: [
    { id: 'brick_laying', title: 'Кладка кирпича', category: 'CONSTRUCTION' },
    { id: 'block_laying', title: 'Кладка блоков', category: 'CONSTRUCTION' },
    { id: 'foundation', title: 'Фундаментные работы', category: 'CONSTRUCTION' },
    { id: 'monolithic', title: 'Монолитные работы', category: 'CONSTRUCTION' },
    { id: 'facade_insulation', title: 'Утепление фасадов', category: 'CONSTRUCTION' },
    { id: 'concrete_works', title: 'Бетонирование', category: 'CONSTRUCTION' },
    { id: 'fence_installation', title: 'Монтаж заборов', category: 'CONSTRUCTION' },
  ],
  WELDING: [
    { id: 'welding_electric', title: 'Электросварка', category: 'WELDING' },
    { id: 'welding_argon', title: 'Аргонная сварка', category: 'WELDING' },
    { id: 'welding_gas', title: 'Газовая сварка', category: 'WELDING' },
    { id: 'welding_semi_auto', title: 'Полуавтоматическая сварка', category: 'WELDING' },
    { id: 'welding_spot', title: 'Точечная сварка', category: 'WELDING' },
    { id: 'welding_pipe', title: 'Сварка труб', category: 'WELDING' },
    { id: 'welding_metal_structures', title: 'Сварка металлоконструкций', category: 'WELDING' },
    { id: 'welding_aluminum', title: 'Сварка алюминия', category: 'WELDING' },
    { id: 'welding_stainless', title: 'Сварка нержавейки', category: 'WELDING' },
  ],
  WINDOWS_DOORS: [
    { id: 'windows_installation', title: 'Установка окон', category: 'WINDOWS_DOORS' },
    { id: 'doors_installation', title: 'Установка дверей', category: 'WINDOWS_DOORS' },
    { id: 'pvc_windows', title: 'Монтаж пластиковых окон', category: 'WINDOWS_DOORS' },
    { id: 'wooden_windows', title: 'Установка деревянных окон', category: 'WINDOWS_DOORS' },
    { id: 'aluminum_windows', title: 'Монтаж алюминиевых окон', category: 'WINDOWS_DOORS' },
    { id: 'entrance_doors', title: 'Установка входных дверей', category: 'WINDOWS_DOORS' },
    { id: 'interior_doors', title: 'Установка межкомнатных дверей', category: 'WINDOWS_DOORS' },
    { id: 'balcony_glazing', title: 'Остекление балконов', category: 'WINDOWS_DOORS' },
    { id: 'window_repair', title: 'Ремонт окон', category: 'WINDOWS_DOORS' },
    { id: 'door_repair', title: 'Ремонт дверей', category: 'WINDOWS_DOORS' },
    { id: 'window_adjustment', title: 'Регулировка окон', category: 'WINDOWS_DOORS' },
    { id: 'door_adjustment', title: 'Регулировка дверей', category: 'WINDOWS_DOORS' },
  ],
  FORGING: [
    { id: 'forged_gates', title: 'Кованые ворота', category: 'FORGING' },
    { id: 'forged_fences', title: 'Кованые заборы', category: 'FORGING' },
    { id: 'forged_railings', title: 'Кованые перила', category: 'FORGING' },
    { id: 'forged_stairs', title: 'Кованые лестницы', category: 'FORGING' },
    { id: 'forged_furniture', title: 'Кованая мебель', category: 'FORGING' },
    { id: 'forged_decor', title: 'Кованый декор', category: 'FORGING' },
    { id: 'forged_gazebo', title: 'Кованые беседки', category: 'FORGING' },
    { id: 'artistic_forging', title: 'Художественная ковка', category: 'FORGING' },
    { id: 'forged_repair', title: 'Ремонт кованых изделий', category: 'FORGING' },
  ],
  INTERIOR_FINISH: [
    { id: 'plastering', title: 'Штукатурные работы', category: 'INTERIOR_FINISH' },
    { id: 'tile_laying', title: 'Укладка плитки', category: 'INTERIOR_FINISH' },
    { id: 'drywall', title: 'Монтаж гипсокартона', category: 'INTERIOR_FINISH' },
    { id: 'wallpaper', title: 'Поклейка обоев', category: 'INTERIOR_FINISH' },
    { id: 'painting', title: 'Покраска стен', category: 'INTERIOR_FINISH' },
    { id: 'laminate', title: 'Укладка ламината', category: 'INTERIOR_FINISH' },
    { id: 'ceiling', title: 'Монтаж потолков', category: 'INTERIOR_FINISH' },
    { id: 'putty', title: 'Шпаклевка стен', category: 'INTERIOR_FINISH' },
    { id: 'carpentry', title: 'Столярные работы', category: 'INTERIOR_FINISH' },
    { id: 'furniture_assembly', title: 'Сборка мебели', category: 'INTERIOR_FINISH' },
  ],
  EXTERIOR_FINISH: [
    { id: 'facade_works', title: 'Фасадные работы', category: 'EXTERIOR_FINISH' },
    { id: 'roofing', title: 'Кровельные работы', category: 'EXTERIOR_FINISH' },
    { id: 'soft_roof', title: 'Монтаж мягкой кровли', category: 'EXTERIOR_FINISH' },
    { id: 'metal_roof', title: 'Монтаж металлочерепицы', category: 'EXTERIOR_FINISH' },
    { id: 'roof_waterproofing', title: 'Гидроизоляция крыши', category: 'EXTERIOR_FINISH' },
    { id: 'roof_insulation', title: 'Утепление кровли', category: 'EXTERIOR_FINISH' },
    { id: 'gutters', title: 'Установка водостоков', category: 'EXTERIOR_FINISH' },
  ],
  ELECTRICAL: [
    { id: 'wiring', title: 'Электропроводка', category: 'ELECTRICAL' },
    { id: 'lighting', title: 'Освещение', category: 'ELECTRICAL' },
    { id: 'automation', title: 'Автоматизация', category: 'ELECTRICAL' },
    { id: 'socket_installation', title: 'Установка розеток', category: 'ELECTRICAL' },
    { id: 'switch_installation', title: 'Установка выключателей', category: 'ELECTRICAL' },
    { id: 'electrical_diagnostics', title: 'Диагностика электропроводки', category: 'ELECTRICAL' },
    { id: 'video_surveillance', title: 'Видеонаблюдение', category: 'ELECTRICAL' },
    { id: 'security_systems', title: 'Охранные системы', category: 'ELECTRICAL' },
  ],
  PLUMBING: [
    { id: 'pipe_installation', title: 'Монтаж труб', category: 'PLUMBING' },
    { id: 'sanitary_installation', title: 'Установка сантехники', category: 'PLUMBING' },
    { id: 'heating', title: 'Отопление', category: 'PLUMBING' },
    { id: 'toilet_installation', title: 'Установка унитаза', category: 'PLUMBING' },
    { id: 'bath_installation', title: 'Установка ванны', category: 'PLUMBING' },
    { id: 'pipe_repair', title: 'Ремонт труб', category: 'PLUMBING' },
    { id: 'drain_cleaning', title: 'Устранение засоров', category: 'PLUMBING' },
    { id: 'faucet_replacement', title: 'Замена смесителя', category: 'PLUMBING' },
    { id: 'radiator_installation', title: 'Монтаж радиаторов', category: 'PLUMBING' },
    { id: 'boiler_installation', title: 'Установка котлов', category: 'PLUMBING' },
  ],
  AUTO_SERVICE: [
    { id: 'engine_repair', title: 'Ремонт двигателей', category: 'AUTO_SERVICE' },
    { id: 'transmission_repair', title: 'Ремонт коробок передач', category: 'AUTO_SERVICE' },
    { id: 'chassis_repair', title: 'Ремонт ходовой части', category: 'AUTO_SERVICE' },
    { id: 'brake_system_repair', title: 'Ремонт тормозной системы', category: 'AUTO_SERVICE' },
    { id: 'steering_repair', title: 'Ремонт рулевого управления', category: 'AUTO_SERVICE' },
    { id: 'suspension_repair', title: 'Ремонт подвески', category: 'AUTO_SERVICE' },
    { id: 'transmission_repair', title: 'Ремонт трансмиссии', category: 'AUTO_SERVICE' },
    { id: 'clutch_repair', title: 'Ремонт сцепления', category: 'AUTO_SERVICE' },
    { id: 'driveshaft_repair', title: 'Ремонт карданного вала', category: 'AUTO_SERVICE' },
    { id: 'gearbox_repair', title: 'Ремонт редуктора', category: 'AUTO_SERVICE' },
    { id: 'differential_repair', title: 'Ремонт дифференциала', category: 'AUTO_SERVICE' },
    { id: 'axle_repair', title: 'Ремонт мостов', category: 'AUTO_SERVICE' },
    { id: 'air_suspension_repair', title: 'Ремонт пневмоподвески', category: 'AUTO_SERVICE' },
    { id: 'air_system_repair', title: 'Ремонт пневмосистемы', category: 'AUTO_SERVICE' },
    { id: 'hydraulic_repair', title: 'Ремонт гидравлики', category: 'AUTO_SERVICE' },
    { id: 'fuel_system_repair', title: 'Ремонт топливной системы', category: 'AUTO_SERVICE' },
    { id: 'injection_system_repair', title: 'Ремонт системы впрыска', category: 'AUTO_SERVICE' },
    { id: 'ignition_system_repair', title: 'Ремонт системы зажигания', category: 'AUTO_SERVICE' },
    { id: 'cooling_system_repair', title: 'Ремонт системы охлаждения', category: 'AUTO_SERVICE' },
    { id: 'lubrication_system_repair', title: 'Ремонт системы смазки', category: 'AUTO_SERVICE' },
    { id: 'ventilation_system_repair', title: 'Ремонт системы вентиляции', category: 'AUTO_SERVICE' },
    { id: 'air_conditioning_repair', title: 'Ремонт системы кондиционирования', category: 'AUTO_SERVICE' },
    { id: 'heating_system_repair', title: 'Ремонт системы отопления', category: 'AUTO_SERVICE' },
    { id: 'lighting_system_repair', title: 'Ремонт системы освещения', category: 'AUTO_SERVICE' },
    { id: 'alarm_system_repair', title: 'Ремонт системы сигнализации', category: 'AUTO_SERVICE' },
    { id: 'safety_system_repair', title: 'Ремонт системы безопасности', category: 'AUTO_SERVICE' },
    { id: 'comfort_system_repair', title: 'Ремонт системы комфорта', category: 'AUTO_SERVICE' },
    { id: 'multimedia_system_repair', title: 'Ремонт системы мультимедиа', category: 'AUTO_SERVICE' },
    { id: 'navigation_system_repair', title: 'Ремонт системы навигации', category: 'AUTO_SERVICE' },
    { id: 'diagnostic_system_repair', title: 'Ремонт системы диагностики', category: 'AUTO_SERVICE' }
  ],
  LANDSCAPING: [
    { id: 'lawn', title: 'Газон', category: 'LANDSCAPING' },
    { id: 'irrigation', title: 'Системы полива', category: 'LANDSCAPING' },
    { id: 'planting', title: 'Озеленение', category: 'LANDSCAPING' },
    { id: 'tree_planting', title: 'Посадка деревьев', category: 'LANDSCAPING' },
    { id: 'paths', title: 'Устройство дорожек', category: 'LANDSCAPING' },
    { id: 'landscape_lighting', title: 'Ландшафтное освещение', category: 'LANDSCAPING' },
    { id: 'paving', title: 'Укладка брусчатки', category: 'LANDSCAPING' },
    { id: 'ponds', title: 'Устройство водоемов', category: 'LANDSCAPING' },
    { id: 'small_architecture', title: 'Малые архитектурные формы', category: 'LANDSCAPING' },
  ],
  CLEANING: [
    { id: 'regular_cleaning', title: 'Регулярная уборка', category: 'CLEANING' },
    { id: 'deep_cleaning', title: 'Генеральная уборка', category: 'CLEANING' },
    { id: 'after_repair', title: 'Уборка после ремонта', category: 'CLEANING' },
    { id: 'window_cleaning', title: 'Мытье окон', category: 'CLEANING' },
    { id: 'furniture_cleaning', title: 'Химчистка мебели', category: 'CLEANING' },
    { id: 'disinfection', title: 'Дезинфекция', category: 'CLEANING' },
    { id: 'territory_cleaning', title: 'Уборка территории', category: 'CLEANING' },
  ],
  OTHER: [
    { id: 'other_services', title: 'Прочие услуги', category: 'OTHER' },
    { id: 'loading', title: 'Погрузка/разгрузка', category: 'OTHER' },
    { id: 'demolition', title: 'Демонтаж', category: 'OTHER' },
    { id: 'garbage_removal', title: 'Вывоз мусора', category: 'OTHER' },
    { id: 'cargo_transportation', title: 'Грузоперевозки', category: 'OTHER' },
  ],
  DRILLING: [
    { id: 'diamond-drilling', title: 'Алмазное бурение', category: 'DRILLING' },
    { id: 'well-drilling', title: 'Скважинное бурение', category: 'DRILLING' },
    { id: 'geological-drilling', title: 'Геологоразведочное бурение', category: 'DRILLING' },
    { id: 'foundation-drilling', title: 'Бурение под фундамент', category: 'DRILLING' },
    { id: 'pile-drilling', title: 'Бурение под сваи', category: 'DRILLING' },
    { id: 'water-drilling', title: 'Бурение под воду', category: 'DRILLING' }
  ],
  AGRICULTURE: [
    { id: 'combine', title: 'Комбайны', category: 'AGRICULTURE' },
    { id: 'tractor', title: 'Тракторы', category: 'AGRICULTURE' },
    { id: 'plowing', title: 'Пахота', category: 'AGRICULTURE' },
    { id: 'harvesting', title: 'Сбор урожая', category: 'AGRICULTURE' },
    { id: 'fertilizing', title: 'Удобрение', category: 'AGRICULTURE' },
    { id: 'sowing', title: 'Посев', category: 'AGRICULTURE' },
    { id: 'irrigation', title: 'Орошение', category: 'AGRICULTURE' },
    { id: 'spraying', title: 'Опрыскивание', category: 'AGRICULTURE' },
    { id: 'planting', title: 'Посадка', category: 'AGRICULTURE' },
    { id: 'cleaning', title: 'Уборка', category: 'AGRICULTURE' }
  ],
  HEATING: [
    { id: 'underfloor_heating', title: 'Тёплые полы', category: 'HEATING' },
    { id: 'boiler_installation', title: 'Установка котлов', category: 'HEATING' },
    { id: 'radiator_installation', title: 'Монтаж радиаторов', category: 'HEATING' },
    { id: 'pipe_installation', title: 'Монтаж труб отопления', category: 'HEATING' },
    { id: 'wall_heating', title: 'Монтаж тёплых стен', category: 'HEATING' },
    { id: 'baseboard_heating', title: 'Монтаж тёплого плинтуса', category: 'HEATING' },
    { id: 'infrared_heating', title: 'Монтаж инфракрасного отопления', category: 'HEATING' },
    { id: 'electric_heating', title: 'Монтаж электрического отопления', category: 'HEATING' },
    { id: 'gas_heating', title: 'Монтаж газового отопления', category: 'HEATING' },
    { id: 'solid_fuel_boiler', title: 'Монтаж твердотопливных котлов', category: 'HEATING' },
    { id: 'heat_pump', title: 'Монтаж тепловых насосов', category: 'HEATING' },
    { id: 'solar_collector', title: 'Монтаж солнечных коллекторов', category: 'HEATING' },
    { id: 'water_heater', title: 'Монтаж бойлеров', category: 'HEATING' },
    { id: 'heating_automation', title: 'Монтаж автоматики отопления', category: 'HEATING' },
    { id: 'heating_service', title: 'Обслуживание и ремонт систем отопления', category: 'HEATING' },
    { id: 'euro_heating', title: 'Евроотопление', category: 'HEATING' },
    { id: 'convector_installation', title: 'Монтаж конвекторов', category: 'HEATING' },
    { id: 'fan_coil_installation', title: 'Монтаж фанкойлов', category: 'HEATING' },
    { id: 'climate_system_installation', title: 'Монтаж климатических систем', category: 'HEATING' }
  ],
  CEILINGS: [
    { id: 'stretch_ceiling', title: 'Натяжные потолки', category: 'CEILINGS' },
    { id: 'suspended_ceiling', title: 'Подвесные потолки', category: 'CEILINGS' },
    { id: 'drywall_ceiling', title: 'Гипсокартонные потолки', category: 'CEILINGS' },
    { id: 'slat_ceiling', title: 'Реечные потолки', category: 'CEILINGS' },
    { id: 'cassette_ceiling', title: 'Кассетные потолки', category: 'CEILINGS' },
    { id: 'mirror_ceiling', title: 'Зеркальные потолки', category: 'CEILINGS' },
    { id: 'multi_level_ceiling', title: 'Многоуровневые потолки', category: 'CEILINGS' }
  ],
  FLOOR_SCREED: [
    { id: 'cement_screed', title: 'Цементная стяжка', category: 'FLOOR_SCREED' },
    { id: 'dry_screed', title: 'Сухая стяжка', category: 'FLOOR_SCREED' },
    { id: 'semi_dry_screed', title: 'Полусухая стяжка', category: 'FLOOR_SCREED' },
    { id: 'self_leveling_screed', title: 'Самовыравнивающаяся стяжка', category: 'FLOOR_SCREED' },
    { id: 'warm_screed', title: 'Теплая стяжка', category: 'FLOOR_SCREED' },
    { id: 'finish_screed', title: 'Финишная стяжка', category: 'FLOOR_SCREED' },
    { id: 'liquid_floor', title: 'Жидкий пол', category: 'FLOOR_SCREED' }
  ],
  SPECIAL_EQUIPMENT: [
    { id: 'excavator', title: 'Экскаватор', category: 'SPECIAL_EQUIPMENT' },
    { id: 'bulldozer', title: 'Бульдозер', category: 'SPECIAL_EQUIPMENT' },
    { id: 'crane', title: 'Автокран', category: 'SPECIAL_EQUIPMENT' },
    { id: 'dump_truck', title: 'Самосвал', category: 'SPECIAL_EQUIPMENT' },
    { id: 'concrete_mixer', title: 'Бетономешалка', category: 'SPECIAL_EQUIPMENT' },
    { id: 'asphalt_paver', title: 'Асфальтоукладчик', category: 'SPECIAL_EQUIPMENT' },
    { id: 'roller', title: 'Каток', category: 'SPECIAL_EQUIPMENT' },
    { id: 'loader', title: 'Погрузчик', category: 'SPECIAL_EQUIPMENT' },
    { id: 'aerial_platform', title: 'Автовышка', category: 'SPECIAL_EQUIPMENT' },
    { id: 'manipulator', title: 'Манипулятор', category: 'SPECIAL_EQUIPMENT' },
    { id: 'concrete_pump', title: 'Бетононасос', category: 'SPECIAL_EQUIPMENT' },
    { id: 'concrete_mixer_truck', title: 'Автобетоносмеситель', category: 'SPECIAL_EQUIPMENT' },
    { id: 'tractor', title: 'Трактор', category: 'SPECIAL_EQUIPMENT' },
    { id: 'grader', title: 'Грейдер', category: 'SPECIAL_EQUIPMENT' },
    { id: 'scraper', title: 'Скрепер', category: 'SPECIAL_EQUIPMENT' },
    { id: 'motor_grader', title: 'Автогрейдер', category: 'SPECIAL_EQUIPMENT' },
    { id: 'pipe_layer', title: 'Трубоукладчик', category: 'SPECIAL_EQUIPMENT' },
    { id: 'crane_manipulator', title: 'Кран-манипулятор', category: 'SPECIAL_EQUIPMENT' },
    { id: 'truck_crane_manipulator', title: 'Автокран-манипулятор', category: 'SPECIAL_EQUIPMENT' },
    { id: 'drilling_equipment', title: 'Спецтехника для бурения', category: 'SPECIAL_EQUIPMENT' }
  ],
  CARGO_TRANSPORT: [
    { id: 'furniture_transport', title: 'Перевозка мебели', category: 'CARGO_TRANSPORT' },
    { id: 'construction_materials_transport', title: 'Перевозка строительных материалов', category: 'CARGO_TRANSPORT' },
    { id: 'appliance_transport', title: 'Перевозка бытовой техники', category: 'CARGO_TRANSPORT' },
    { id: 'food_transport', title: 'Перевозка продуктов', category: 'CARGO_TRANSPORT' },
    { id: 'clothing_transport', title: 'Перевозка одежды', category: 'CARGO_TRANSPORT' },
    { id: 'document_transport', title: 'Перевозка документов', category: 'CARGO_TRANSPORT' },
    { id: 'equipment_transport', title: 'Перевозка оборудования', category: 'CARGO_TRANSPORT' },
    { id: 'inventory_transport', title: 'Перевозка инвентаря', category: 'CARGO_TRANSPORT' },
    { id: 'tool_transport', title: 'Перевозка инструментов', category: 'CARGO_TRANSPORT' },
    { id: 'cargo_transport', title: 'Перевозка грузов', category: 'CARGO_TRANSPORT' },
    { id: 'building_materials_transport', title: 'Перевозка стройматериалов', category: 'CARGO_TRANSPORT' }
  ],
  BODY_REPAIR: [
    { id: 'body_painting', title: 'Покраска кузова', category: 'BODY_REPAIR' },
    { id: 'paintless_dent_repair', title: 'Рихтовка без покраски', category: 'BODY_REPAIR' },
    { id: 'paintless_dent_removal', title: 'Удаление вмятин без покраски', category: 'BODY_REPAIR' },
    { id: 'body_geometry_restoration', title: 'Восстановление геометрии кузова', category: 'BODY_REPAIR' },
    { id: 'anti_corrosion_treatment', title: 'Антикоррозийная обработка', category: 'BODY_REPAIR' }
  ],
  AUTO_DETAILING: [
    { id: 'interior_cleaning', title: 'Химчистка салона', category: 'AUTO_DETAILING' },
    { id: 'body_polishing', title: 'Полировка кузова', category: 'AUTO_DETAILING' },
    { id: 'ceramic_coating', title: 'Обработка кузова керамикой', category: 'AUTO_DETAILING' },
    { id: 'liquid_glass', title: 'Обработка кузова жидким стеклом', category: 'AUTO_DETAILING' },
    { id: 'wax_coating', title: 'Обработка кузова воском', category: 'AUTO_DETAILING' },
    { id: 'teflon_coating', title: 'Обработка кузова тефлоном', category: 'AUTO_DETAILING' },
    { id: 'nano_ceramic', title: 'Обработка кузова нанокерамикой', category: 'AUTO_DETAILING' },
    { id: 'anti_gravel', title: 'Обработка кузова антигравием', category: 'AUTO_DETAILING' },
    { id: 'anti_rain', title: 'Обработка кузова антидождь', category: 'AUTO_DETAILING' },
    { id: 'anti_dirt', title: 'Обработка кузова антигрязь', category: 'AUTO_DETAILING' },
    { id: 'steam_treatment', title: 'Паровая обработка', category: 'AUTO_DETAILING' },
    { id: 'protective_film', title: 'Оклейка защитной пленкой', category: 'AUTO_DETAILING' },
    { id: 'armor_film', title: 'Оклейка бронепленкой', category: 'AUTO_DETAILING' },
    { id: 'chip_filling', title: 'Заливка сколов', category: 'AUTO_DETAILING' },
    { id: 'scratch_removal', title: 'Удаление царапин', category: 'AUTO_DETAILING' }
  ],
  HANDYMAN: [
    { id: 'loader', title: 'Грузчик', category: 'HANDYMAN' },
    { id: 'helper', title: 'Подсобник', category: 'HANDYMAN' },
    { id: 'construction_helper', title: 'Разнорабочий на стройке', category: 'HANDYMAN' },
    { id: 'cleaner', title: 'Уборщик территории', category: 'HANDYMAN' },
    { id: 'warehouse_helper', title: 'Помощник на складе', category: 'HANDYMAN' },
    { id: 'mover', title: 'Такелажник', category: 'HANDYMAN' },
    { id: 'demolition_worker', title: 'Рабочий по демонтажу', category: 'HANDYMAN' },
    { id: 'yardman', title: 'Дворник', category: 'HANDYMAN' },
    { id: 'gardener', title: 'Садовник', category: 'HANDYMAN' },
    { id: 'handyman_general', title: 'Универсальный разнорабочий', category: 'HANDYMAN' },
  ],
};

export const categoryTitles: Record<ServiceCategory, string> = {
  CONSTRUCTION: 'Строительство',
  INTERIOR_FINISH: 'Внутренняя отделка',
  ELECTRICAL: 'Электрика',
  PLUMBING: 'Сантехника',
  AUTO_SERVICE: 'Автосервис',
  EXTERIOR_FINISH: 'Внешняя отделка',
  LANDSCAPING: 'Ландшафтный дизайн',
  CLEANING: 'Уборка',
  WELDING: 'Сварочные работы',
  WINDOWS_DOORS: 'Окна и двери',
  FORGING: 'Кованые изделия',
  OTHER: 'Другое',
  DRILLING: 'Бурение',
  AGRICULTURE: 'Сельское хозяйство',
  HEATING: 'Отопление',
  CEILINGS: 'Потолки',
  FLOOR_SCREED: 'Стяжка пола',
  SPECIAL_EQUIPMENT: 'Спецтехника',
  CARGO_TRANSPORT: 'Грузоперевозки',
  BODY_REPAIR: 'Кузовные работы',
  AUTO_DETAILING: 'Авто детейлинг',
  HANDYMAN: 'Разнорабочие',
};

// Заглушка для categories, чтобы не было ошибки импорта
export const categories: string[] = []; 